; PHP General Settings
memory_limit = 1024M
max_execution_time = 600
max_input_time = 60
error_reporting = E_ALL
display_errors = On
log_errors = On
error_log = /var/log/php-error.log
date.timezone = Japan
allow_url_fopen = On
allow_url_include = Off
max_file_uploads = 20
default_socket_timeout = 60
html_errors = On
expose_php = On
short_open_tag = Off
precision = 14
output_buffering = 4096

; Upload Settings
file_uploads = On
upload_max_filesize = 500M
post_max_size = 500M

; Session Settings
session.save_handler = files
session.save_path = "/tmp"
session.use_strict_mode = 0
session.use_cookies = 1
session.use_only_cookies = 1
session.name = PHPSESSID
session.auto_start = 0
session.cookie_lifetime = 0
session.cookie_path = /
session.cookie_domain =
session.cookie_httponly =
session.serialize_handler = php
session.gc_probability = 1
session.gc_divisor = 1000
session.gc_maxlifetime = 1440
session.referer_check =
session.cache_limiter = nocache
session.cache_expire = 180
session.use_trans_sid = 0
session.sid_length = 26
session.trans_sid_tags = "a=href,area=href,frame=src,form="
session.sid_bits_per_character = 5

; APCu Settings
apc.enabled = 1
apc.enable_cli = 1
apc.shm_size = 64M

; Opcache Settings
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 4000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2

; Locales
intl.default_locale = en_US

; XDebug Settings
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal
xdebug.client_port=9004
xdebug.log=/tmp/xdebug.log

; Optional profiling settings
# xdebug.trigger_value=1
# xdebug.output_dir=/tmp
# xdebug.profiler_output_name=cachegrind.out.%t-%s

; Optional tracing settings
# xdebug.trace_output_name=trace.%t