# project2 Docker Compose | php7.4 | apache2.4

services:
  php:
    build:
      context: ../..
      dockerfile: projects/project2/Dockerfile
    container_name: project2_php
    volumes:
      - ./testsrc:/var/www/html
      # - ./src:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      # Enable the following lines to use global configs after creating/adding the files
      # Make sure to set correct permissions for the files (especially git private keys 600)
      # - ../../global-configs/.gitconfig:/var/www/.gitconfig
      # - ../../global-configs/.ssh:/var/www/.ssh
    ports:
      - "9001:9001"
    networks:
      - shared-network

  apache:
    image: httpd:2.4
    container_name: project2_apache
    volumes:
      - ./testsrc:/var/www/html
      # - ./src:/var/www/html
      - ./apache.conf:/usr/local/apache2/conf/httpd.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.project2.rule=Host(`project2.localhost`)"
      - "traefik.http.services.project2.loadbalancer.server.port=80"
    networks:
      - shared-network
    depends_on:
      - php

networks:
  shared-network:
    external: true
